---
name: LLVM

on:
  pull_request:
    paths: [.github/workflows/llvm.yml, bootstrap_llvm.sh]
  push:
    paths: [.github/workflows/llvm.yml, bootstrap_llvm.sh]
  workflow_dispatch:

jobs:
  build_linux:
    strategy:
      fail-fast: false
      matrix:
        llvm: ["17.0.3"]
        os: ["ubuntu-20.04"]

    name: linux-llvm-${{ matrix.llvm }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache/restore@v3
        with: { key: linux-ccache, path: ~/.cache/ccache }
      - uses: actions/cache/restore@v3
        with: { key: "linux-llvm-${{ matrix.llvm }}", path: llvm-project/ }

      - name: Install cmake + ccache + ninja
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-{recommends,suggests} cmake ccache ninja-build
      - name: Install clang + lld
        if: matrix.os != 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-{recommends,suggests} clang lld

      # NOTE(jcmdln): Ubuntu 20.04 requires handling errata
      - name: (Ubuntu 20.04) Install clang-12 + lld-12
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-{recommends,suggests} {clang,lld}-12
      - name: (Ubuntu 20.04) Make Clang/LLVM 12 the default
        if: matrix.os == 'ubuntu-20.04'
        run: |
          sudo ln -sf /usr/bin/clang-12   /usr/bin/clang
          sudo ln -sf /usr/bin/clang++-12 /usr/bin/clang++
          sudo ln -sf /usr/bin/lld-12     /usr/bin/lld
      - name: (Ubuntu 20.04) Setup newer CMake for LLVM-17
        if: matrix.os == 'ubuntu-20.04'
        uses: jwlawson/actions-setup-cmake@v1.14.1
        with: { cmake-version: "3.x" }

      - name: Bootstrap LLVM + Odin
        env:
          CC: /usr/bin/clang-12
          CC_LD: /usr/bin/lld-12
          CXX: /usr/bin/clang++-12
          CXX_LD: /usr/bin/lld-12
          LD: /usr/bin/lld-12
          LLVM_BRANCH: llvmorg-${{ matrix.llvm }}
        run: ./bootstrap_llvm.sh

      - name: Odin version
        run: ./odin version
        timeout-minutes: 1
        working-directory: Odin
      - name: Odin report
        run: ./odin report
        timeout-minutes: 1
        working-directory: Odin
      - name: Odin check
        run: ./odin check examples/demo -vet
        timeout-minutes: 10
        working-directory: Odin
      - name: Odin run
        run: ./odin run examples/demo
        timeout-minutes: 10
        working-directory: Odin
      - name: Odin run -debug
        run: ./odin run examples/demo -debug
        timeout-minutes: 10
        working-directory: Odin
      - name: Odin check examples/all
        run: ./odin check examples/all -strict-style
        timeout-minutes: 10
        working-directory: Odin
      - name: Core library tests
        run: make
        timeout-minutes: 10
        working-directory: Odin/tests/core
      - name: Odin internals tests
        run: make
        timeout-minutes: 10
        working-directory: Odin/tests/internal
      - name: Odin check examples/all for Linux i386
        run: ./odin check examples/all -vet -strict-style -target:linux_i386
        timeout-minutes: 10
        working-directory: Odin
      - name: Odin check examples/all for FreeBSD amd64
        run: ./odin check examples/all -vet -strict-style -target:freebsd_amd64
        timeout-minutes: 10
        working-directory: Odin
      - name: Odin check examples/all for OpenBSD amd64
        run: ./odin check examples/all -vet -strict-style -target:openbsd_amd64
        timeout-minutes: 10
        working-directory: Odin

      - uses: actions/cache/save@v3
        if: github.ref_name == 'master'
        with: { key: linux-ccache, path: ~/.cache/ccache }
      - uses: actions/cache/save@v3
        if: github.ref_name == 'master'
        with: { key: "linux-llvm-${{ matrix.llvm }}", path: llvm-project/ }

      # TODO(jcmdln): actions/upload-artifact breaks file permissions
      # TODO(jcmdln): https://github.com/actions/upload-artifact/issues/38
      - uses: actions/upload-artifact@v3
        if: github.repository == 'jcmdln/odin-bootstrap'
        with:
          name: odin-linux-llvm-${{ matrix.llvm }}
          path: |
            Odin/core/
            Odin/examples/
            Odin/vendor/
            Odin/LICENSE
            Odin/odin
